-- AlterTable
ALTER TABLE "accounts" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0.00;

-- AlterTable
ALTER TABLE "transactions" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0.00;
